version: '2'
services:
        run-api-backend:
                build: ./api-backend
                ports:
                        - "8001:8001"
                networks:
                        - bridge
                restart: always

        run-api-frontend:
                build: ./api-frontend
                ports:
                        - "8000:8000"
                networks:
                        - bridge
                restart: always

networks:
        bridge:
